- name: common
  src: git+https://github.com/estribiyo/ansible-common.git
- name: ohmyzsh
  src: git+https://github.com/estribiyo/ansible-ohmyzsh.git
- name: screen
  src: git+https://github.com/estribiyo/ansible-gnuscreen.git
- name: devel-generic
  src: git+https://github.com/estribiyo/ansible-devel-generic
- name: devel-php
  src: git+https://github.com/estribiyo/ansible-devel-php.git
- name: ispconfig
  src: git+https://github.com/estribiyo/ansible-ispconfig.git
- name: telegraf
  src: git+https://github.com/estribiyo/ansible-telegraf.git
- name: docker
  src: git+https://github.com/estribiyo/ansible-docker.git  
